// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config"; // 1. Added the 'env' utility here

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 2. Changed this from process.env.DATABASE_URL to your unpooled variable
    url: env("DATABASE_URL_UNPOOLED"), 
  },
});
